name: dart_rtc_server
version: 0.1.0
author: Sami Ylonen <sami.ylonen@gmail.com>
description: A Dart WebRTC signaling server
dependencies:
  args: any
  dart_rtc_common:
    git: git://github.com/samiy-xx/dart_rtc_common.git
  logging_handlers: 0.5.0+2
  unittest: 0.5.5
